# Header
menu:
  HOME: /
  ARCHIVES: /archives
  '#RANDOM': /categories/Category-1/random/
  CONTACT: /contact/

footer_icons:
  'Hexo.io':
    url: 'https://hexo.io/'
    class: 'fas fa-home'
  '@hexojs':
    url: 'https://twitter.com/hexojs'
    class: 'fab fa-twitter'
  'Report issue':
    url: 'https://github.com/RandomAdversary/Gradient/issues'
    class: 'fas fa-bug'


sidebar:
  twitter:
    username: 'hexojs'
    height: 800
  tldr: 'Gradient is clean and modern hexo theme.'

featured_image: ./img/default.jpg